In [1]:
from scipy.spatial.transform import Rotation as R
import numpy as np

In [2]:
class cubesat:
   def __init__(self, designation):
    """
    Generates a CubeSat with a Designation as User Specified, '1U' or '3U' or '6U', etc.
    Make the vertices of the CubeSat"""

    self.designation = designation

    if designation == '1U':
      self.vertices = np.array([[0, 0, 0],[10, 0, 0],[10, 10, 0],[0, 10, 0],[0, 0, 10],[10, 0, 10],[10, 10, 10],[0, 10, 10]])

    if designation == '3U':
      self.vertices = np.array([[0, 0, 0],[10, 0, 0],[10, 10, 0],[0, 10, 0],[0, 0, 30],[10, 0, 30],[10, 10, 30],[0, 10, 30]])
    
   def get_vertices(self):
     self.vertex_1 = self.vertices[0]
     self.vertex_2 = self.vertices[1]
     self.vertex_3 = self.vertices[2]
     self.vertex_4 = self.vertices[3]
     self.vertex_5 = self.vertices[4]
     self.vertex_6 = self.vertices[5]
     self.vertex_7 = self.vertices[6]
     self.vertex_8 = self.vertices[7]

   def get_edges(self):
     self.edge_1to2 = self.vertex_2 - self.vertex_1
     self.edge_2to3 = self.vertex_3 - self.vertex_2
     self.edge_3to4 = self.vertex_4 - self.vertex_3
     self.edge_4to1 = self.vertex_1 - self.vertex_4
     self.edge_5to6 = self.vertex_6 - self.vertex_5
     self.edge_6to7 = self.vertex_7 - self.vertex_6
     self.edge_7to8 = self.vertex_8 - self.vertex_7
     self.edge_8to5 = self.vertex_5 - self.vertex_8
     self.edge_1to5 = self.vertex_5 - self.vertex_1
     self.edge_2to6 = self.vertex_6 - self.vertex_2
     self.edge_3to7 = self.vertex_7 - self.vertex_3
     self.edge_4to8 = self.vertex_8 - self.vertex_4
     
   def rotate(self, body_frame_vector,angle_degrees):
    pass

In [3]:
a = cubesat('1U')
print(a.vertices)

[[ 0  0  0]
 [10  0  0]
 [10 10  0]
 [ 0 10  0]
 [ 0  0 10]
 [10  0 10]
 [10 10 10]
 [ 0 10 10]]


In [4]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
c = b @ a.vertices.T
c

array([[ 0., 10., 10.,  0.,  0., 10., 10.,  0.],
       [ 0.,  0., 10., 10.,  0.,  0., 10., 10.],
       [ 0.,  0.,  0.,  0., 10., 10., 10., 10.]])

In [6]:
a.get_vertices()
a.vertex_8 - a.vertex_7

array([-10,   0,   0])

In [9]:
from SpawnFunctions import *

In [10]:
print('\nTesting the "spawn_cameras" function')
list_of_cameras, dataframe = spawn_cameras(
    wing_dimension=500,
    no_of_telephotos=4,
    telephoto_distribution=2,
    no_of_mediumranges=12,
    mediumrange_distribution=50,
    no_of_wideangles=30,
    wideangle_distribution=100,
)
dataframe


Testing the "spawn_cameras" function


NameError: name 'spawn_cameras' is not defined